# Generated by Django 3.1.4 on 2020-12-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='T',
        ),
        migrations.RemoveField(
            model_name='input',
            name='b',
        ),
        migrations.RemoveField(
            model_name='input',
            name='w',
        ),
        migrations.AddField(
            model_name='input',
            name='B',
            field=models.FloatField(default=71.0, verbose_name=' grid '),
        ),
        migrations.AddField(
            model_name='input',
            name='C',
            field=models.FloatField(default=1.0, verbose_name=' Length '),
        ),
        migrations.AddField(
            model_name='input',
            name='D',
            field=models.FloatField(default=2.0, verbose_name=' Uwall'),
        ),
        migrations.AddField(
            model_name='input',
            name='E',
            field=models.FloatField(default=0.05, verbose_name=' nu '),
        ),
        migrations.AddField(
            model_name='input',
            name='F',
            field=models.FloatField(default=0.0003, verbose_name=' deltat '),
        ),
        migrations.AlterField(
            model_name='input',
            name='A',
            field=models.IntegerField(default=4000, verbose_name=' maxstep '),
        ),
    ]
